# A boolean to remove raster entries whose file is not on the volume
deleteStaleEntries: true

# A boolean to delete files on the volume older than the oldest ingested raster entry
deleteStaleFiles: true

# The desired disk volume cache location
#diskVolumes:
#    data:
#        mount: /data/s3
#        databases:
#            database1:
#                driverClassName: ${omarDb.driver}
#                url: ${omarDb.url}
#                username: ${omarDb.username}
#                password: ${omarDb.password}


# Whether or not you actually want to delete files and database entires
dryRun: false

# The maximum disk space percentage that can be reached before deletion begins
maxDiskLimit: 0.95

# The disk space percentage to reach before deletetion stops
minDiskLimit: 0.94

# How often ( in  milliseconds ) to run
repeatInterval: 600000

# Location of the stager URL
stagerUrl: http://omar-stager-app:8080/omar-stager

---
grails:
    profile: web
    codegen:
        defaultPackage: omar.disk.cleanup
    spring:
        transactionManagement:
            proxies: false
    gorm:
        reactor:
            # Whether to translate GORM events into Reactor events
            # Disabled by default for performance reasons
            events: false
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false

# Spring Actuator Endpoints are Disabled by Default
endpoints:
    enabled: true
    jmx:
        enabled: true

---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlets: html
                taglib: none
                staticparts: none
endpoints:
    jmx:
        unique-names: true

---
hibernate:
    cache:
        queries: false
        use_second_level_cache: false
        use_query_cache: false
dataSource:
    pooled: true
    jmxExport: true
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres

environments:
    development:
        dataSource:
            dbCreate: update
            url: jdbc:postgresql://localhost:5432/omar_db
    test:
        dataSource:
            dbCreate: update
            url: jdbc:postgresql://localhost:5432/omar_db
    production:
        dataSource:
            dbCreate: update
            url: jdbc:postgresql://localhost:5432/omar_db
            properties:
                jmxEnabled: true
                initialSize: 5
                maxActive: 50
                minIdle: 5
                maxIdle: 25
                maxWait: 10000
                maxAge: 600000
                timeBetweenEvictionRunsMillis: 5000
                minEvictableIdleTimeMillis: 60000
                validationQuery: SELECT 1
                validationQueryTimeout: 3
                validationInterval: 15000
                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: false
                jdbcInterceptors: ConnectionState
                defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED
